### ISSUE TITLE
请问，此服务可以用来做下载服务器吗？如何可以，需要如何测试？

### ISSUE THREAD

**Issue by wuqingwei** [taozhijiang/tzhttpd#2]

**Comment by taozhijiang** [comment]
没明白下载服务器是用来做什么的，有什么样的特殊需求。

本库传递静态资源都是全部读到内存中，然后逐步发送给客户端的，应该说没有对大文件传输、分块重传等功能做优化。
使用的话直接在example中bash build.sh就可以编译出一个可执行的服务端，默认配置文件就可以跑起来

**Comment by wuqingwei** [comment]
> 没明白下载服务器是用来做什么的，有什么样的特殊需求。
> 
> 本库传递静态资源都是全部读到内存中，然后逐步发送给客户端的，应该说没有对大文件传输、分块重传等功能做优化。
> 使用的话直接在example中bash build.sh就可以编译出一个可执行的服务端，默认配置文件就可以跑起来

谢谢回复。
就是类似nginx的http下载功能，需要支持大文件传输，支持断点续传

**Comment by taozhijiang** [comment]
tzhttpd主要被优化实现应用程序网关的，不适合用来做通用的静态服务器。

你可以在Handler中实现这种功能，欢迎PR
